# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comm',
        ),
    ]
